---

repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint
        entry: markdownlint
        language: node
        types: [markdown]
        additional_dependencies: ['commander']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: Check swift files
        name: swiftlint
        entry: bash
        args: ["-c", "swiftlint --strict"]
        always_run: true
        language: system
